name: publish to nuget

on: [push, pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "build"
  build_pack_publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
          
      - name: Checkout
        run: git fetch --tags

      - name: Fetch master for GitVersion
        if: github.ref != 'refs/heads/main'
        run: git branch --create-reflog master origin/main
        
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
    
      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.x"
          
      - name: Build solution and generate NuGet package
        run: |
          dotnet pack -c Release -o out -p:PackageVersion=${{ steps.gitversion.outputs.semVer }}

      - name: Push HttpClient to GitHub registry
        run: dotnet nuget push ./out/SugarChat.Net.Client.${{ steps.gitversion.outputs.semVer }}.nupkg --skip-duplicate --no-symbols true -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
          
      - name: Push Message to GitHub registry
        run: dotnet nuget push ./out/SugarChat.Message.${{ steps.gitversion.outputs.semVer }}.nupkg --skip-duplicate --no-symbols true -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
