name: publish to nuget
on:
  push:
    branches: [ ]     
jobs:
  build:
    name: Get Git Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get Git Version
        uses: docker://mcasperson/gitversion:5.0.2-linux-centos-7-netcoreapp2.2
        with:
          args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""
      - name: Extract Octopus Tools
        run: |
          mkdir /opt/octo
          cd /opt/octo
          wget -O /opt/octo/octopus.zip https://download.octopusdeploy.com/octopus-tools/6.12.0/OctopusTools.6.12.0.portable.zip
          unzip /opt/octo/octopus.zip
          chmod +x /opt/octo/Octo
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200    

      #Publish Message
      - name: publish on message version change
        id: publish_message_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/SugarChat.Message/SugarChat.Message.csproj       

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}


      # Publish Client
      - name: publish on client version change
        id: publish_client_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/SugarChat.Net.Client/SugarChat.Net.Client.csproj       

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
